### PR TITLE
fix(api)!: TIP compliance for `history` API fields

### LINKED ISSUE #312: Make `LedgerUpdateResponse` fully TIP-compliant
* [x] `paging_state` should be `cursor`
* [x] `transaction_id` and `output_index` should be `outputId`
* [x] `data` should be `items`
* [x] All fields should use camelCase

### PR DESCRIPTION
**Pull request by grtlr**
Closes #312.

### CODE REVIEW

**Review by Alexandcoats — APPROVED** [review]

File: bin/inx-chronicle/src/api/stardust/history/responses.rs [hunk 1]
```diff
@@ -10,18 +10,16 @@ use crate::api::impl_success_response;
 #[derive(Clone, Debug, Serialize, Deserialize)]
 pub struct TransactionHistoryResponse {
     pub address: String,
-    pub transactions: Vec<Transfer>,
-    pub paging_state: Option<String>,
+    pub items: Vec<Transfer>,
```
Comment (Alex6323) [inline bin/inx-chronicle/src/api/stardust/history/responses.rs:13]: Since the elements of the vec are `Transfer`s, why not call this field `transfers` then? :trollface:

File: bin/inx-chronicle/src/api/stardust/history/routes.rs [hunk 2]
```diff
@@ -68,8 +67,8 @@ async fn transaction_history(
         .collect::<Result<_, ApiError>>()?;
 
     Ok(TransactionHistoryResponse {
-        transactions,
+        items: transactions,
```
[the remark this answers is not in the document]
Comment (grtlr) [reply bin/inx-chronicle/src/api/stardust/history/routes.rs:70]: But `transactions` is already ambiguous :trollface:, because the list contains outputs. I think we should do a renaming path once the TIP has settled.

File: bin/inx-chronicle/src/api/stardust/history/responses.rs (hunk 1 above)
Comment (grtlr) [reply bin/inx-chronicle/src/api/stardust/history/responses.rs:13]: Because @Alexandcoats came up with `Transfer`, but we could not agree on it yet. 😁
