### PR TITLE
fix(db): create indexes on `.milestone_index`

### LINKED ISSUE #714: Output indexes should be on `MilestoneIndex` instead of `MilestoneIndexTimestamp`
When we do this change, we should also rename the indexes so that users don't have to delete and recreate indexes.

### PR DESCRIPTION
**Pull request by grtlr**
Closes #714.

### CODE REVIEW

**Review by Alex6323 — DISMISSED** [review]

File: src/db/collections/outputs/indexer/mod.rs [hunk 1]
```diff
@@ -392,10 +392,10 @@ impl OutputCollection {
 
         self.create_index(
             IndexModel::builder()
-                .keys(doc! { "metadata.booked": -1 })
+                .keys(doc! { "metadata.booked.milestone_index": -1 })
                 .options(
                     IndexOptions::builder()
-                        .name("output_booked_index".to_string())
+                        .name("output_booked_milestone_index".to_string())
                         .partial_filter_expression(doc! { "metadata.spent_metadata": null })
```
Comment (Alexandcoats) [inline src/db/collections/outputs/indexer/mod.rs:399]: We should really also remove this filter. None of our queries that use this index specify it.

File: src/db/collections/outputs/indexer/mod.rs [hunk 2]
```diff
@@ -406,11 +406,11 @@ impl OutputCollection {
...
         self.create_index(
             IndexModel::builder()
-                .keys(doc! { "metadata.spent_metadata.spent": -1 })
+                .keys(doc! { "metadata.spent_metadata.spent.milestone_index": -1 })
                 .options(
                     IndexOptions::builder()
-                        .name("output_spent_index".to_string())
-                        .partial_filter_expression(doc! { "metadata.spent_metadata.spent": { "$exists": true } })
+                        .name("output_spent_milestone_index".to_string())
+                        .partial_filter_expression(doc! { "metadata.spent_metadata": { "$exists": true } })
```
Comment (Alexandcoats) [inline src/db/collections/outputs/indexer/mod.rs:413]: I believe this must specify down to the milestone index field.

**Review by Alexandcoats — APPROVED** [review]

**Review by Alex6323 — APPROVED** [review]
lgtm
