### PR TITLE
fix(db): add `unlock_condition` to `id_index`

### LINKED ISSUE #400: `id_index` on `LedgerUpdateDocument` is not unique
Because multiple addresses can "own" an an output through the different unlock conditions. It could even be that the same address appears in the different unlock conditions of the same output.

### PR DESCRIPTION
**Pull request by grtlr**
Closes #400.

### CODE REVIEW

File: src/db/collections/ledger_update.rs [hunk 1]
```diff
@@ -140,12 +143,14 @@ impl MongoDb {
             let is_spent = metadata.spent.is_some();
 
             // Ledger updates
-            for owner in output.owning_addresses() {
+            for (address, unlock_condition) in output.owning_addresses() {
```
Comment (Alex6323) [inline src/db/collections/ledger_update.rs:146]: `unlock_condition_desc` is probably clearer to not confuse it with the "real" `UnlockCondition` type.

File: src/db/collections/ledger_update.rs [hunk 2]
```diff
@@ -25,6 +25,9 @@ struct LedgerUpdateDocument {
     address: Address,
     output_id: OutputId,
     at: MilestoneIndexTimestamp,
+    #[serde(with = "crate::types::util::stringify")]
+    amount: u64,
+    unlock_condition: UnlockConditionDescription,
```
Comment (Alex6323) [inline src/db/collections/ledger_update.rs:30]: consider naming it `unlock_condition_desc`?

File: src/types/stardust/block/output/unlock_condition.rs [hunk 3]
```diff
@@ -35,16 +35,44 @@ pub enum UnlockCondition {
     },
 }
 
+#[derive(Copy, Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
+#[serde(rename_all = "snake_case", tag = "kind")]
+pub enum UnlockConditionDescription {
```
Comment (Alex6323) [inline src/types/stardust/block/output/unlock_condition.rs:40]: I really don't like this additional type. Tbh it just bloats the code base.

**Review by Alex6323 — APPROVED** [review]
