### PR TITLE
fix(api): remove `inx` from `is_healthy` check

### LINKED ISSUE #414: Remove `inx` check from `is_healthy`
This does not play nicely with runtime configuration of features.

### PR DESCRIPTION
**Pull request by grtlr**
Closes #414.

### CODE REVIEW

File: bin/inx-chronicle/src/api/routes.rs [hunk 1]
```diff
@@ -8,22 +8,26 @@ use axum::{
...
 };
-use chronicle::{db::MongoDb, runtime::ScopeView};
+use chronicle::db::MongoDb;
 use hyper::StatusCode;
 use serde::Deserialize;
+use time::{Duration, OffsetDateTime};
 
 use super::{auth::Auth, config::ApiData, error::ApiError, responses::*, ApiResult};
 
+const STALE_MILESTONE_DURATION: Duration = Duration::minutes(1);
```
Comment (Alex6323) [inline bin/inx-chronicle/src/api/routes.rs:18]: Can you document this constant and why we think 1 minute is a good heuristic?

**Review by Alex6323 — DISMISSED** [review]
