### PR TITLE
fix(api): add max page size and tests

### LINKED ISSUE #440: Add upper bound for page sizes in APIs
Otherwise an attacker could, for example, send huge queries for addresses that are frequently used (like the faucet).

### PR DESCRIPTION
**Pull request by Alexandcoats**
Closes #440

### CODE REVIEW

File: bin/inx-chronicle/src/api/error.rs [hunk 1]
```diff
@@ -109,17 +109,17 @@ pub enum ParseError {
...
     BadPagingState,
-    #[error("Invalid sort order descriptor")]
-    BadSortDescriptor,
     #[cfg(feature = "stardust")]
     #[error(transparent)]
     BeeBlockStardust(#[from] bee_block_stardust::Error),
     #[error(transparent)]
     Bool(#[from] ParseBoolError),
     #[error(transparent)]
+    DecimalU256(#[from] uint::FromDecStrErr),
```
Comment (grtlr) [inline bin/inx-chronicle/src/api/error.rs:118]: Love the alphabetic ordering!

File: src/db/collections/ledger_update.rs [hunk 2]
```diff
@@ -50,12 +53,35 @@ pub struct LedgerUpdateByMilestoneRecord {
...
 }
 
+impl Default for SortOrder {
+    fn default() -> Self {
+        Self::Newest
+    }
+}
+
+#[derive(Debug, Error)]
+#[error("Invalid sort order descriptor. Expected 'oldest' or 'newest', found '{0}'")]
```
Comment (grtlr) [inline src/db/collections/ledger_update.rs:69]:
```suggestion
#[error("Invalid sort order descriptor. Expected `oldest` or `newest`, found `{0}`")]
```

**Review by grtlr — APPROVED** [review]
